# Generated by Django 5.0.7 on 2024-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='category',
            new_name='categories',
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('categories', models.ManyToManyField(to='website.category')),
            ],
        ),
    ]
