# Generated by Django 5.0.7 on 2024-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_donation_address_donation_city_donation_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
